export const SET_DOCUMENT_CHANGED = 'SET_DOCUMENT_CHANGED'
export const SET_CURRENT_DOCUMENT = 'SET_CURRENT_DOCUMENT'
export const SET_CURRENT_COMMIT_DESCRIPTION = 'SET_CURRENT_COMMIT_DESCRIPTION'

export const COMMIT_CHANGES = '@@editor/COMMIT_CHANGES'
export const COMMIT_CHANGES_FAILURE = '@@editor/COMMIT_CHANGES_FAILURE'
export const COMMIT_CHANGES_SUCCESS = '@@editor/COMMIT_CHANGES_SUCCESS'
