export enum ResourceInfoBarColourScheme {
  GreyScaleLight,
  GreyScaleDark,
  Primary,
  SecondaryLight,
  SecondaryDark,
  Tertiary,
  Red,
  Green,
}

export const colourSchemeMapping = {
  [ResourceInfoBarColourScheme.Primary]: {
    leadingForeground: 'onPrimaryM30',
    leadingBackground: 'primaryM30',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'primaryP60',
    mainBorder: 'primary',
    trailingForeground: 'onPrimary',
    trailingBackground: 'primary',
  },
  [ResourceInfoBarColourScheme.GreyScaleLight]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'black',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'lightGrey',
    mainBorder: 'grey',
    trailingForeground: 'onPrimary',
    trailingBackground: 'grey',
  },
  [ResourceInfoBarColourScheme.GreyScaleDark]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'black',
    mainForeground: 'onGrey',
    mainBackground: 'grey',
    mainBorder: 'black',
    trailingForeground: 'onPrimary',
    trailingBackground: 'black',
  },
  [ResourceInfoBarColourScheme.SecondaryLight]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'secondary',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'secondaryP60',
    mainBorder: 'secondaryP20',
    trailingForeground: 'onPrimary',
    trailingBackground: 'secondaryP20',
  },
  [ResourceInfoBarColourScheme.SecondaryDark]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'secondaryDark',
    mainForeground: 'onPrimary',
    mainBackground: 'secondaryDark',
    mainBorder: 'secondaryDark',
    trailingForeground: 'onPrimary',
    trailingBackground: 'secondary',
  },
  [ResourceInfoBarColourScheme.Tertiary]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'tertiary',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'tertiaryP60',
    mainBorder: 'tertiaryP20',
    trailingForeground: 'onPrimary',
    trailingBackground: 'tertiaryP20',
  },
  [ResourceInfoBarColourScheme.Red]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'red',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'redP60',
    mainBorder: 'redP20',
    trailingForeground: 'onPrimary',
    trailingBackground: 'redP20',
  },
  [ResourceInfoBarColourScheme.Green]: {
    leadingForeground: 'onPrimary',
    leadingBackground: 'green',
    mainForeground: 'onPrimaryP30',
    mainBackground: 'greenP60',
    mainBorder: 'greenP20',
    trailingForeground: 'onPrimary',
    trailingBackground: 'greenP20',
  },
}
