export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const TOGGLE_DEMO_MODE = 'TOGGLE_DEMO_MODE'
export const LOGIN_ACCESS_CHECK = 'LOGIN_ACCESS_CHECK'
